# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='amount',
            field=models.FloatField(default=50, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='bet',
            name='month',
            field=models.IntegerField(default=7, verbose_name='Mes'),
        ),
        migrations.AddField(
            model_name='bet',
            name='odds',
            field=models.FloatField(default=1.85, verbose_name='Odds'),
        ),
        migrations.AddField(
            model_name='bet',
            name='pick',
            field=models.CharField(default='Default', max_length=200, verbose_name='Pick'),
        ),
        migrations.AddField(
            model_name='bet',
            name='sport',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sport'),
        ),
        migrations.AddField(
            model_name='bet',
            name='stake',
            field=models.FloatField(default=0.1, verbose_name='Stake'),
        ),
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('W', 'Win'), ('L', 'Lost'), ('N', 'Null')], default='P', max_length=1, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='bet',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
