# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_auto_20170702_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='tipster',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipster'),
        ),
    ]
