# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_auto_20170703_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='sport',
        ),
        migrations.AddField(
            model_name='bet',
            name='event',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Event'),
        ),
    ]
