# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_auto_20170706_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
