# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.FloatField(blank=True, null=True, verbose_name='Bank'),
        ),
        migrations.AddField(
            model_name='account',
            name='bookie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bookie'),
        ),
    ]
