# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170702_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank',
            field=models.FloatField(default=1000, verbose_name='Bank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='bookie',
            field=models.CharField(default='bet365', max_length=100, verbose_name='Bookie'),
            preserve_default=False,
        ),
    ]
